print("hello my name is Stephen Orban")
print("today is Wednesday, September the 22nd")
print("there isn't really a bad time to use a management software when working on a project")
print("a time when it is necesarry though is when you are working in a group on a code")
print("that way you can be more organized with who is doing what as well as the changes that are being made")
print("for example, Git allows you to create a project and set guidlines to it")
print("that way you can make it private or public as well as adding a description of the project")
print("you can also choose a license and tell people what they can and can not do with your code")
print("again, you don't need to use one when you are by yourself but it wouldnt be a bad to thing since it could keep track of things for you")
